FROM java:8-jdk-alpine

COPY ./target/LoginApplication-0.0.1-SNAPSHOT.jar .

WORKDIR .

RUN sh -c 'touch LoginApplication-0.0.1-SNAPSHOT.jar'

ENTRYPOINT ["java","-jar","LoginApplication-0.0.1-SNAPSHOT.jar"]