spring:
  datasource:
    username: admin
    password: 1qaz2wsx
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mora-demo-rds.cufpstswot1b.us-east-2.rds.amazonaws.com:3306/testapp

  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect